kind: Service
apiVersion: v1
metadata:
  name: esb
  labels:
    app: esb
spec:
  type: ClusterIP
  selector:
    app: esb
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: esb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esb
  template:
    metadata:
      labels:
        app: esb
        version: v1
    spec:
      containers:
      - name: esb
        image: esb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
