server:
  port: 8080
  host: 0.0.0.0
  # features:
  #   static-content:
  #     temporary-storage:
  #       directory: "./target/helidon/tmp"
  #       file-prefix: "helidon-custom"
  #       file-suffix: ".cache"
  #       # delete-on-exit: false
  #     content-types:
  #       # ico: "image/x-icon"
  #       html: "text/html"
  #       # css: "text/css"
  #       # js: "text/javascript"
  # classpath:
  #   - context: "/"
  #     location: "/essapp"
  # content-types:
  #   # ico: "image/x-icon"
  #   html: "text/html"
  #   css: "text/css"
  #   js: "text/javascript"
  # html: "application/xhtml+xml"
  # css: "text/css"
  # js: "application/javascript"

app:
  greeting: "Hello"
